### ISSUE TITLE
traversing through multiple folders

### ISSUE THREAD

**Issue by nikunj2512** [ox-it/python-sharepoint#13]
I got this problem while fetching the list of rows inside a folder.

This is the structure of my sharepoint.

A -> F ->E->test.doc
B
C
D
E
(A-E -> all are folders)

server_url = "https://server/"
password_manager = urllib2.HTTPPasswordMgrWithDefaultRealm()
password_manager.add_password(None, server_url, 'username', 'password')
auth_handler = HTTPNtlmAuthHandler.HTTPNtlmAuthHandler(password_manager)
opener = urllib2.build_opener(auth_handler)
site = SharePointSite(server_url, opener)
shared_docs = site.lists.all_lists[0]  # to get the first folder A
shared_docs_rows = shared_docs.rows
vow_action_plan = shared_docs_rows[0]  # to get the Folder F

Now i want to go inside the Folder E and get the list of documents in the Folder E but i am unable to do so.

**Comment by chris-bradley** [comment]
This can be done if you apply the following commits:
 - ninemoreminutes/python-sharepoint/@df38f8642ac9d3ca5ad138085a0846ccd9443e6c
 - emergence/python-sharepoint/@c7b4f8049ce5b4c21abcce9ddda5cc32eaf76554

You would then be able to do:
```
shared_docs.get_rows(folder='/A/F/E')
```
to get the contents of folder E.

**Comment by alexsdutton** [comment]
Fixed in #17
