### ISSUE TITLE
error iterating over rows - no attribute 'FieldName'

### ISSUE THREAD

**Issue by cgc17** [ox-it/python-sharepoint#15]
following the documentation and running (after successfully connecting and setting ```sp_list = site.lists['sitename']```):
```python
for row in sp_list.rows:
    print row.id, row.FieldName
```
returns this error:

```AttributeError: 'SharePointListRow' object has no attribute 'FieldName'```

Any ideas on this one, or am I missing something?

**Comment by alexsdutton** [comment]
Sorry, `FieldName` should be an actual field name. You can find which ones you have available by looking at `sp_list.fields`.

**Comment by cgc17** [comment]
Oops. Thanks for pointing that out!
