### ISSUE TITLE
"pip install sharepoint" broken

### ISSUE THREAD

**Issue by denizdogan** [ox-it/python-sharepoint#2]
> (test-sp) C:\repos\test\code\python\sp>pip install sharepoint
> Downloading/unpacking sharepoint
>   Running setup.py egg_info for package sharepoint
>     Traceback (most recent call last):
>       File "<string>", line 16, in <module>
>       File "C:\Users\deniz.dogan.virtualenvs\test-sp\build\sharepoint\setup.py", line 10, in <module>
>         long_description=open('README.rst').read(),
>     IOError: [Errno 2] No such file or directory: 'README.rst'
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>   File "<string>", line 16, in <module>
> 
>   File "C:\Users\deniz.dogan.virtualenvs\test-sp\build\sharepoint\setup.py", line 10, in <module>
> 
> ```
> long_description=open('README.rst').read(),
> ```
> 
> IOError: [Errno 2] No such file or directory: 'README.rst'
> ---
> 
> Command python setup.py egg_info failed with error code 1 in C:\Users\deniz.dogan.virtualenvs\test-sp\build\sharepoint
> Storing complete log in C:\Users\deniz.dogan\pip\pip.log

**Comment by isaiahakello** [comment]
@alexsdutton  if am trying to install pip sharepoint and i get no matching distribution found for sharepoint what could it be?
